# Generated by Django 5.2.8 on 2025-11-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizador'), ('attendee', 'Asistente'), ('client', 'Cliente')], max_length=10),
        ),
    ]
